### ISSUE TITLE
Use keyboardShouldPersistTaps in ScrollView on post writing screen

### ISSUE THREAD

**Issue by brentvatne** [jonsamp/gray-one#1]
`keyboardShouldPersistTaps="always"` prop on ScrollView lets you tap on things inside a ScrollView when the keyboard is open and have the tap register as a press on the first tap, rather than having to tap once to dismiss the keybefore and then tap again for onPress to fire.

**Comment by jonsamp** [comment]
Thanks for the tip! I didn't know this was an option. Added!
